name = "KinodynamicFabrics"
uuid = "afbb1a1e-07e5-4f58-b27b-4ddb5ca69c13"
authors = ["Alphonsus Adu-Bredu"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DigitInterface = "eaae82b0-39d2-4257-bb05-ac4059402812"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gauntlet = "63b46612-4817-4105-9884-ec370fe8c371"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
