[lowlevelapi]
enable = true
# Time in seconds between Low-level API packets before control program
# disables robot
timeout = 0.05
# Port for incoming and outgoing Low-level API communications.
# Change if these settings interfere with any other programs or network
# Traffic on the payload computer. Must match settings in lowlevelapi.c
# (lines 181 and 183). These should not be changed under normal operation
listen-port = 25500
send-port = 25501

[simulator]
# Low-level API is only functional with dynamic simulator
# dynamic = true

# Enable perfect state for better visualization, but it will cause some state estimate features to be disabled (e.g. foot contact reporting)
perfect-state = false

# If false, the simulator does not run faster than real-time.
free-run = false

# Add robot to simulation fixed above the ground
[[model-list]]
model = "robot"
# pose = {rpyxyzd = [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]} # 1.12, 1.2  1.571   # in degrees
# pose = {rpyxyzd = [0.0, 0.0, 45.0, 0.0, 0.0, 1.0]} # 1.12, 1.2  
pose = {rpyxyzd = [0.0, 0.0, 90.0, 0.0, 0.0, 1.0]} # 1.12, 1.2  
fixed = false

[simulator.robot]
# initial-operation-mode = "locomotion"
initial-configuration = "test-stand"

